language: ruby
rvm:
  - 2.2.3

services:
  - mysql

addons:
  code_climate:
    repo_token: 5889714a5b60b1a58cfb1737c0fd228e3098236a9609805850c10fac7ebf718a

script:
  - bin/rake db:create RAILS_ENV=test
  - bin/rake db:migrate RAILS_ENV=test
  - bundle exec rake

after_success:
  - bundle exec codeclimate-test-reporter